version: 3

dotenv: ['.env']

env:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org,direct


tasks:
  local-release:
    cmds:
      - cmd: mv dist/reverse-tunnel_linux_amd64_v1/reverse-tunnel {{.MY_INFINITY_HOME}}/.dave-programs/

  setup:
    desc: Install dependencies
    cmds:
      - go mod tidy
  fmt:
    desc: gofumpt all code
    cmds:
      - gofmt -w -l .
        #- gofumpt -w -l .

  reverse-tunnel:
    cmds:
      - go run main.go --action=reverse-tunnel

  port-forwarding:
    env:
      REMOTE_ENDPOINT_HOST: '127.0.0.0'
      REMOTE_ENDPOINT_PORT: '8082'
      LOCAL_ENDPOINT_PORT: 8000
      LOCAL_ENDPOINT_HOST: 'localhost'
    cmds:
      #- echo $LOCAL_ENDPOINT_PORT
      - go run main.go --action=port-forwarding


  release:
    desc: Create a new tag
    vars:
      NEXT:
        sh: svu n
    cmds:
      - git tag {{.NEXT}}
      - echo {{.NEXT}}
        #- git push origin --tags

  build:
    desc: Build the binary
    sources:
      - ./**/*.go
    generates:
      - ./goreleaser
    cmds:
      - go build

  goreleaser:
    desc: Run GoReleaser either in snapshot or release mode
    deps:
      - build
    vars:
      SNAPSHOT:
        sh: 'if [[ $GITHUB_REF != refs/tags/v* ]]; then echo "--snapshot"; fi'
    cmds:
      - goreleaser release --clean --timeout 60m {{.SNAPSHOT}}
